version: 2

sources:
  - name: staging
    database: dtc-de-course-375810
    schema: trips_data_all

    tables:
      - name: green_tripdata_2019_2020
      - name: yellow_tripdata_2019_2020
      - name: fhv_2019
      